# Generated by Django 3.1.5 on 2021-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('article', models.TextField()),
                ('slug', models.SlugField()),
                ('pubdate', models.DateTimeField(verbose_name='Published Date')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
